version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: KnitWit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: knitwitadmin
      MINIO_SECRET_KEY: knitwitadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  app:
    image: knitwit
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/KnitWit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      MINIO_URL: http://minio:9000
      MINIO_USERNAME: knitwitadmin
      MINIO_PASSWORD: knitwitadmin
      MINIO_BUCKETNAME: knitwit
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio_data:
