version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: KnitWit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - knitwit-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - knitwit-network

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: knitwitadmin
      MINIO_ROOT_PASSWORD: knitwitadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - knitwit-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: knitwitadmin
      KEYCLOAK_ADMIN_PASSWORD: knitwitadmin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    command:
      - start-dev
    networks:
      - knitwit-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knitwit_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/KnitWit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_MINIO_URL: http://minio:9000
      SPRING_MINIO_USERNAME: knitwitadmin
      SPRING_MINIO_PASSWORD: knitwitadmin
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: KnitWit-Realm
      KEYCLOAK_CLIENT_ID: KnitWit-Client
      KEYCLOAK_CLIENT_SECRET: drZaprYRwKYR0SlgJENVUsjiPGpmsY2k
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - minio
      - keycloak
    networks:
      - knitwit-network

volumes:
  postgres-data:
  minio-data:
  pgadmin-data:
  keycloak-data:

networks:
  knitwit-network: