version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: KnitWit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: knitwitadmin
      MINIO_ROOT_PASSWORD: knitwitadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knitwit_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/KnitWit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_MINIO_URL: http://minio:9000
      SPRING_MINIO_USERNAME: knitwitadmin
      SPRING_MINIO_PASSWORD: knitwitadmin
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - minio

volumes:
  postgres-data:
  minio-data:
