spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/KnitWit
    url: jdbc:postgresql://postgres:5432/KnitWit
    username: KnitWit
    password: KnitWit
    validationQuery: SELECT 1
    testOnBorrow: true

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
  main:
    allow-circular-references: true

minio:
#  url: http://localhost:9000
  url: http://minio:9000
  username: knitwitadmin
  password: knitwitadmin
  bucketName: knitwit

jwt:
  secret: jfdnusighfdoishgfuishfidsb812y37832y47832e1242234324
  lifetime: 7d

server:
  port: 8081