spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/KnitWit
    username: postgres
    password: postgres
    validationQuery: SELECT 1
    testOnBorrow: true

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration

minio:
  url: http://minio:9000
  username: knitwitadmin
  password: knitwitadmin
  bucketName: knitwit

server:
  port: 8081
