spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KnitWit
    username: postgres
    password: postgres
    validationQuery: SELECT 1
    testOnBorrow: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration