spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/KnitWit-Realm
#          issuer-uri: http://keycloak:8080/realms/KnitWit-Realm

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KnitWit
#    url: jdbc:postgresql://postgres:5432/KnitWit
    username: postgres
    password: postgres
    validationQuery: SELECT 1
    testOnBorrow: true

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration

minio:
  url: http://localhost:9000
#  url: http://minio:9000
  username: knitwitadmin
  password: knitwitadmin
  bucketName: knitwit

realm: KnitWit-Realm
server-url: http://localhost:8080
#server-url: http://keycloak:8080
client-id: admin-cli
grant-type: password
name: admin
password: admin

springdoc:
  swagger-ui:
    oauth:
      client-id: KnitWit-Client
      client-secret: drZaprYRwKYR0SlgJENVUsjiPGpmsY2k

server:
  port: 8081